### ISSUE TITLE
Maximum update depth exceeded

### ISSUE THREAD

**Issue by davidb1** [saltycrane/use-fit-text#9]
The state is updated too much and the changes in font size are minuscule:
![image](https://user-images.githubusercontent.com/13868996/90621245-21aa6c00-e21c-11ea-9e44-71aef8050c70.png)

This happens when `maxFontSize` or `minFontSize` aren't integers (they probably should be rounded to up to 2 places or parsed as int)

**Comment by saltycrane** [comment]
Hi @davidb1 thanks for the bug report. Are you passing in the `maxFontSize` and `minFontSize` arguments as strings? They are meant to be passed in as numbers. For example, the following works for me without an error:

```
function Example1() {
  const { fontSize, ref } = useFitText({
    minFontSize: 20.1,
    maxFontSize: 99.9,
  });
  return (
    <>
      <b>Example 1</b>
      <div
        ref={ref}
        style={{ fontSize, height: 40, width: 120, border: "1px solid #ccc" }}
      >
        Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet,
        consectetur
      </div>
      <hr />
    </>
  );
}
```

If you are passing them in as numbers and still have the bug, could you give some example code that demonstrates the bug?

**Comment by davidb1** [comment]
I am using numbers (for max 285.7142857142857 after some calculations). I can't manage to reproduce outside of the project.
I have multiple elements with `useFitText` and one of them keeps getting resized. When I remove some of them, this doesn't happen.
![image](https://user-images.githubusercontent.com/13868996/90673998-2cd3bb00-e261-11ea-8a12-4873bff7071f.png)

**Comment by saltycrane** [comment]
Hi @davidb1, if you come up with some example code that reproduces the bug, I can look into it.

**Comment by davidb1** [comment]
I might be able to. Trying to understand why this part in `use-fit-text` is getting called over and over:
```
    if (isWithinResolution) {
      if (isOverflow) {
        const fontSizeNew =
          fontSizePrev < fontSize
            ? fontSizePrev
            : fontSize - (fontSizePrev - fontSize);
        setState({
          fontSize: fontSizeNew,
          fontSizeMax,
          fontSizeMin,
          fontSizePrev,
          calcKey,
        });
      } else {
        isCalculatingRef.current = false;
        onFinish && onFinish(fontSize);
      }
      return;
    }
```

Any idea what could trigger these checks?

**Comment by saltycrane** [comment]
hi @davidb1, I found some parameters that cause a "Maximum update depth exceeded" error (both are needed to get the error):

- `minFontSize` is set to a value that is larger than the `fontSize` value needed to fit the text in the div
- `onFinish` does not `useCallback` and is created every render so it doesn't compare referentially equal to itself (Unfortunately this causes that [code snippet you referenced](https://github.com/saltycrane/use-fit-text/issues/9#issuecomment-678094921) to run also because I use it in the dependency array of `useLayoutEffect` [here](https://github.com/saltycrane/use-fit-text/blob/877c31334c1cdc0ccfbbc0cc7731f53b8eecb179/index.ts#L167). This is a problem I've run into with React hooks, but am not sure how best to deal with it. It seems like some people handle it by using a library like [`react-fast-compare`](https://github.com/FormidableLabs/react-fast-compare), but AFAIK, it doesn't work with functions.)

Here is my code to reproduce the issue: https://github.com/saltycrane/use-fit-text/blob/master/examples/pages/index.tsx#L109-L138

I pushed a new [`v2.4.0-alpha` package to npm](https://www.npmjs.com/package/use-fit-text/v/2.4.0-alpha) that addresses the issue. It no longer gives the "Maximum update depth exceeded" error for my test case. Instead it logs an error to the console saying the `minFontSize` is too large. Here is the fix in case your are interested: https://github.com/saltycrane/use-fit-text/commit/1ab2138ccc608d9dc2390e2b7ea37ddec8843ede#diff-ed009b6b86b017532ef0489c77de5100

Run `npm install use-fit-text@2.4.0-alpha` to try it. Let me know if this looks like the problem you are having and if the fix works for you.

**Comment by davidb1** [comment]
For me, adding a check to the script eliminated the problem:
```
else if (isOverflow) {
        const fontSizeNew =
          fontSizePrev < fontSize
            ? fontSizePrev
            : fontSize - (fontSizePrev - fontSize);
        if ( fontSize >= fontSizeMin) {   // <---- do not go below minFontSize
        setState({
          fontSize: fontSizeNew,
          fontSizeMax,
          fontSizeMin,
          fontSizePrev,
          calcKey,
        });
        }
```

**Comment by saltycrane** [comment]
hi @davidb1, I pushed a [`2.4.0-alpha.2` version](https://www.npmjs.com/package/use-fit-text/v/2.4.0-alpha.2) to npm. Does that eliminate your error?

**Comment by davidb1** [comment]
Yes it does, thanks. But what if the minimum set size is the fallback that I am ok with? I wouldn't want to see the error

**Comment by saltycrane** [comment]
Glad to hear that fix worked for you. 👍 

> But what if the minimum set size is the fallback that I am ok with? I wouldn't want to see the error

That's a good point-- would you be fine with using `console.info` to log an informational message instead of the error message using `console.error`?

**Comment by davidb1** [comment]
It's better than error but I would be looking into removing that in production env

**Comment by saltycrane** [comment]
hi @davidb1, I added [a `logLevel` option](https://github.com/saltycrane/use-fit-text#usefittextoptions) that allows you to silence the logging if it is unwanted. I pushed [`v2.4.0` to npm](https://www.npmjs.com/package/use-fit-text/v/2.4.0).
